"""Approach view."""
import streamlit as st
TEAL="#0F4C5C"; NAVY="#1E293B"; CRIMSON="#832232"; AMBER="#B8860B"; GREEN="#15803D"; MGRAY="#E2E8F0"; DGRAY="#64748B"
DIMS=[("AC","Awareness Conversion",14,CRIMSON),("IBC","Intent — Behavior",25,NAVY),("MBC","Message — Belief",20,CRIMSON),("RTC","Rep Trust",13,TEAL),("ABR","Access Barrier Resolution",15,NAVY),("KCC","Knowledge Conversion",8,GREEN),("CI","Competitive Influence",5,AMBER)]

def render(eng):
    st.markdown(f'<div style="font-size:10px;text-transform:uppercase;letter-spacing:.22em;color:#94A3B8;font-weight:600;margin-bottom:8px">HOW WE BUILT THIS · METHODOLOGY</div><h1 style="font-family:\'DM Serif Display\',serif;font-size:48px;font-weight:300;color:#0F172A;line-height:1.1;margin-bottom:12px">Three steps from <em>survey data</em><br>to a doctor-specific <span style="color:{TEAL}">field play.</span></h1><p style="font-size:14px;color:#475569;max-width:640px;line-height:1.65;margin-bottom:28px">We unify the ATU survey with the PET. The two datasets meet in the ICI, which sorts every HCP into one of five engagement states. The output is a custom doctor rep support card, generated purely from the data.</p>', unsafe_allow_html=True)
    sc = st.columns(3)
    for col,(num,title,color) in zip(sc,[("STEP 01",f"Calculate the ICI",TEAL),("STEP 02","Cluster every doctor",CRIMSON),("STEP 03","Generate custom rep card",GREEN)]):
        with col: st.markdown(f'<div style="background:white;border:1px solid {MGRAY};border-radius:14px;padding:20px;border-top:4px solid {color}"><div style="font-size:10px;text-transform:uppercase;letter-spacing:.2em;color:{color};font-weight:700;margin-bottom:6px">{num}</div><div style="font-size:15px;font-weight:600;color:#0F172A">{title}</div></div>', unsafe_allow_html=True)
    st.markdown(f"<br>", unsafe_allow_html=True)
    lc, rc = st.columns(2)
    with lc:
        st.markdown(f'<div style="background:white;border:1px solid {MGRAY};border-radius:14px;padding:20px"><div style="font-size:11px;font-weight:600;color:#0F172A;margin-bottom:10px">INPUTS</div><div style="background:#F8FAFC;border-radius:8px;padding:12px;margin-bottom:8px"><div style="font-size:12px;font-weight:600;color:{TEAL}">ATU — Awareness Trial Usage</div><div style="font-size:12px;color:#64748B;margin-top:4px">What doctors say about the product, their intent, patient population</div></div><div style="background:#F8FAFC;border-radius:8px;padding:12px"><div style="font-size:12px;font-weight:600;color:{NAVY}">PET — Promotional Effectiveness Tracker</div><div style="font-size:12px;color:#64748B;margin-top:4px">What they remember from the rep visit, messages recalled, VAs used</div></div></div>', unsafe_allow_html=True)
    with rc:
        st.markdown(f'<div style="background:white;border:1px solid {MGRAY};border-radius:14px;padding:20px"><div style="font-size:11px;font-weight:600;color:#0F172A;margin-bottom:10px">THE SEVEN DIMENSIONS</div>', unsafe_allow_html=True)
        for key,name,weight,color in DIMS:
            st.markdown(f'<div style="display:flex;align-items:center;gap:10px;margin-bottom:8px"><div style="width:160px;font-size:12px;font-weight:500;color:#0F172A">{name} ({key})</div><div style="flex:1;height:7px;background:#F1F5F9;border-radius:99px;overflow:hidden"><div style="width:{weight*5}%;height:100%;background:{color};border-radius:99px"></div></div><div style="width:32px;text-align:right;font-size:12px;font-weight:600;color:#0F172A">{weight}%</div></div>', unsafe_allow_html=True)
        st.markdown(f'<div style="background:{NAVY};color:white;border-radius:8px;padding:10px;font-family:monospace;font-size:11px;line-height:1.9;margin-top:8px">ICI = AC×.14 + IBC×.25 + MBC×.20<br>+ RTC×.13 + ABR×.15 + KCC×.08 + CI×.05</div></div>', unsafe_allow_html=True)

    st.markdown(f"<br><div style='font-size:10px;text-transform:uppercase;letter-spacing:.2em;color:{DGRAY};font-weight:600'>SEQUENTIAL CLUSTERING RULES</div>", unsafe_allow_html=True)
    for num,color,trigger,outcome in [(1,TEAL,"IBC<35 or Gr2PL<3","Patient ID Priority — lead with patient identification"),(2,NAVY,"IBC≥35 AND ABR<45","Access Pending — lead with access toolkit"),(3,CRIMSON,"MBC<35 AND RTC<55","Evidence Gap — address misbelief with data"),(4,AMBER,"AC≥50 AND MBC<55 AND IBC<70","Narrative Build — pick one message, repeat"),(5,GREEN,"All gates cleared","Conviction-Led — partnership, pipeline, advocacy")]:
        st.markdown(f'<div style="display:flex;align-items:flex-start;gap:12px;padding:12px;margin-bottom:6px;background:#F8FAFC;border-radius:10px;border-left:4px solid {color}"><div style="width:26px;height:26px;border-radius:50%;background:{color};display:flex;align-items:center;justify-content:center;color:white;font-weight:700;font-size:12px;flex-shrink:0">{num}</div><div><div style="font-size:10px;text-transform:uppercase;letter-spacing:.15em;color:{color};font-weight:700;margin-bottom:2px">TRIGGER: {trigger}</div><div style="font-size:13px;color:#0F172A">{outcome}</div></div></div>', unsafe_allow_html=True)
